<?php
/**
 * MerchantRegistrationApi
 * PHP version 7.4
 *
 * @category Class
 * @package  MastercardApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Srci Client Onboarding Orch Service API
 *
 * Mastercard Commerce System:  API definitions for Client Onboarding Orch Service.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@mastercard.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace MastercardApiClient\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use MastercardApiClient\ApiException;
use MastercardApiClient\Configuration;
use MastercardApiClient\HeaderSelector;
use MastercardApiClient\ObjectSerializer;

/**
 * MerchantRegistrationApi Class Doc Comment
 *
 * @category Class
 * @package  MastercardApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MerchantRegistrationApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'deleteMerchant' => [
            'application/json',
        ],
        'updateMerchant' => [
            'application/json',
        ],
        'uploadMerchants' => [
            'application/json',
        ],
    ];

/**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation deleteMerchant
     *
     * Delete merchant from Unified Checkout Solutions
     *
     * @param  string $organization_id ID of the SRC system where a merchant is registered. (required)
     * @param  string $srci_dpa_id The SRCI specific ID for the DPA you are registering. This ID should be generated by you and needs to be unique per environment per SRC system. (required)
     * @param  string $correlation_id Unique Id to trace one end to end transaction, Client to ensure uniqueness for every transaction (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteMerchant'] to see the possible values for this operation
     *
     * @throws \MastercardApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function deleteMerchant($organization_id, $srci_dpa_id, $correlation_id = null, string $contentType = self::contentTypes['deleteMerchant'][0])
    {
        $this->deleteMerchantWithHttpInfo($organization_id, $srci_dpa_id, $correlation_id, $contentType);
    }

    /**
     * Operation deleteMerchantWithHttpInfo
     *
     * Delete merchant from Unified Checkout Solutions
     *
     * @param  string $organization_id ID of the SRC system where a merchant is registered. (required)
     * @param  string $srci_dpa_id The SRCI specific ID for the DPA you are registering. This ID should be generated by you and needs to be unique per environment per SRC system. (required)
     * @param  string $correlation_id Unique Id to trace one end to end transaction, Client to ensure uniqueness for every transaction (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteMerchant'] to see the possible values for this operation
     *
     * @throws \MastercardApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteMerchantWithHttpInfo($organization_id, $srci_dpa_id, $correlation_id = null, string $contentType = self::contentTypes['deleteMerchant'][0])
    {
        $request = $this->deleteMerchantRequest($organization_id, $srci_dpa_id, $correlation_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MastercardApiClient\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MastercardApiClient\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MastercardApiClient\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MastercardApiClient\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation deleteMerchantAsync
     *
     * Delete merchant from Unified Checkout Solutions
     *
     * @param  string $organization_id ID of the SRC system where a merchant is registered. (required)
     * @param  string $srci_dpa_id The SRCI specific ID for the DPA you are registering. This ID should be generated by you and needs to be unique per environment per SRC system. (required)
     * @param  string $correlation_id Unique Id to trace one end to end transaction, Client to ensure uniqueness for every transaction (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteMerchant'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteMerchantAsync($organization_id, $srci_dpa_id, $correlation_id = null, string $contentType = self::contentTypes['deleteMerchant'][0])
    {
        return $this->deleteMerchantAsyncWithHttpInfo($organization_id, $srci_dpa_id, $correlation_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation deleteMerchantAsyncWithHttpInfo
     *
     * Delete merchant from Unified Checkout Solutions
     *
     * @param  string $organization_id ID of the SRC system where a merchant is registered. (required)
     * @param  string $srci_dpa_id The SRCI specific ID for the DPA you are registering. This ID should be generated by you and needs to be unique per environment per SRC system. (required)
     * @param  string $correlation_id Unique Id to trace one end to end transaction, Client to ensure uniqueness for every transaction (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteMerchant'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteMerchantAsyncWithHttpInfo($organization_id, $srci_dpa_id, $correlation_id = null, string $contentType = self::contentTypes['deleteMerchant'][0])
    {
        $returnType = '';
        $request = $this->deleteMerchantRequest($organization_id, $srci_dpa_id, $correlation_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'deleteMerchant'
     *
     * @param  string $organization_id ID of the SRC system where a merchant is registered. (required)
     * @param  string $srci_dpa_id The SRCI specific ID for the DPA you are registering. This ID should be generated by you and needs to be unique per environment per SRC system. (required)
     * @param  string $correlation_id Unique Id to trace one end to end transaction, Client to ensure uniqueness for every transaction (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteMerchant'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function deleteMerchantRequest($organization_id, $srci_dpa_id, $correlation_id = null, string $contentType = self::contentTypes['deleteMerchant'][0])
    {

        // verify the required parameter 'organization_id' is set
        if ($organization_id === null || (is_array($organization_id) && count($organization_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $organization_id when calling deleteMerchant'
            );
        }

        // verify the required parameter 'srci_dpa_id' is set
        if ($srci_dpa_id === null || (is_array($srci_dpa_id) && count($srci_dpa_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $srci_dpa_id when calling deleteMerchant'
            );
        }



        $resourcePath = '/org/{organization_id}/dpas/{srci_dpa_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($correlation_id !== null) {
            $headerParams['correlation-id'] = ObjectSerializer::toHeaderValue($correlation_id);
        }

        // path params
        if ($organization_id !== null) {
            $resourcePath = str_replace(
                '{' . 'organization_id' . '}',
                ObjectSerializer::toPathValue($organization_id),
                $resourcePath
            );
        }
        // path params
        if ($srci_dpa_id !== null) {
            $resourcePath = str_replace(
                '{' . 'srci_dpa_id' . '}',
                ObjectSerializer::toPathValue($srci_dpa_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation updateMerchant
     *
     * Update DPA data
     *
     * @param  string $organization_id ID of the SRC system where a merchant is registered. (required)
     * @param  string $srci_dpa_id The SRCI specific ID for the DPA you are registering. This ID should be generated by you and needs to be unique per environment per SRC system. (required)
     * @param  \MastercardApiClient\Model\UpdateDpaRequest $update_dpa_request update_dpa_request (required)
     * @param  string $correlation_id Unique Id to trace one end to end transaction, Client to ensure uniqueness for every transaction (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateMerchant'] to see the possible values for this operation
     *
     * @throws \MastercardApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function updateMerchant($organization_id, $srci_dpa_id, $update_dpa_request, $correlation_id = null, string $contentType = self::contentTypes['updateMerchant'][0])
    {
        $this->updateMerchantWithHttpInfo($organization_id, $srci_dpa_id, $update_dpa_request, $correlation_id, $contentType);
    }

    /**
     * Operation updateMerchantWithHttpInfo
     *
     * Update DPA data
     *
     * @param  string $organization_id ID of the SRC system where a merchant is registered. (required)
     * @param  string $srci_dpa_id The SRCI specific ID for the DPA you are registering. This ID should be generated by you and needs to be unique per environment per SRC system. (required)
     * @param  \MastercardApiClient\Model\UpdateDpaRequest $update_dpa_request (required)
     * @param  string $correlation_id Unique Id to trace one end to end transaction, Client to ensure uniqueness for every transaction (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateMerchant'] to see the possible values for this operation
     *
     * @throws \MastercardApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateMerchantWithHttpInfo($organization_id, $srci_dpa_id, $update_dpa_request, $correlation_id = null, string $contentType = self::contentTypes['updateMerchant'][0])
    {
        $request = $this->updateMerchantRequest($organization_id, $srci_dpa_id, $update_dpa_request, $correlation_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MastercardApiClient\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MastercardApiClient\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MastercardApiClient\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MastercardApiClient\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation updateMerchantAsync
     *
     * Update DPA data
     *
     * @param  string $organization_id ID of the SRC system where a merchant is registered. (required)
     * @param  string $srci_dpa_id The SRCI specific ID for the DPA you are registering. This ID should be generated by you and needs to be unique per environment per SRC system. (required)
     * @param  \MastercardApiClient\Model\UpdateDpaRequest $update_dpa_request (required)
     * @param  string $correlation_id Unique Id to trace one end to end transaction, Client to ensure uniqueness for every transaction (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateMerchant'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateMerchantAsync($organization_id, $srci_dpa_id, $update_dpa_request, $correlation_id = null, string $contentType = self::contentTypes['updateMerchant'][0])
    {
        return $this->updateMerchantAsyncWithHttpInfo($organization_id, $srci_dpa_id, $update_dpa_request, $correlation_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation updateMerchantAsyncWithHttpInfo
     *
     * Update DPA data
     *
     * @param  string $organization_id ID of the SRC system where a merchant is registered. (required)
     * @param  string $srci_dpa_id The SRCI specific ID for the DPA you are registering. This ID should be generated by you and needs to be unique per environment per SRC system. (required)
     * @param  \MastercardApiClient\Model\UpdateDpaRequest $update_dpa_request (required)
     * @param  string $correlation_id Unique Id to trace one end to end transaction, Client to ensure uniqueness for every transaction (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateMerchant'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateMerchantAsyncWithHttpInfo($organization_id, $srci_dpa_id, $update_dpa_request, $correlation_id = null, string $contentType = self::contentTypes['updateMerchant'][0])
    {
        $returnType = '';
        $request = $this->updateMerchantRequest($organization_id, $srci_dpa_id, $update_dpa_request, $correlation_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'updateMerchant'
     *
     * @param  string $organization_id ID of the SRC system where a merchant is registered. (required)
     * @param  string $srci_dpa_id The SRCI specific ID for the DPA you are registering. This ID should be generated by you and needs to be unique per environment per SRC system. (required)
     * @param  \MastercardApiClient\Model\UpdateDpaRequest $update_dpa_request (required)
     * @param  string $correlation_id Unique Id to trace one end to end transaction, Client to ensure uniqueness for every transaction (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateMerchant'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function updateMerchantRequest($organization_id, $srci_dpa_id, $update_dpa_request, $correlation_id = null, string $contentType = self::contentTypes['updateMerchant'][0])
    {

        // verify the required parameter 'organization_id' is set
        if ($organization_id === null || (is_array($organization_id) && count($organization_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $organization_id when calling updateMerchant'
            );
        }

        // verify the required parameter 'srci_dpa_id' is set
        if ($srci_dpa_id === null || (is_array($srci_dpa_id) && count($srci_dpa_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $srci_dpa_id when calling updateMerchant'
            );
        }

        // verify the required parameter 'update_dpa_request' is set
        if ($update_dpa_request === null || (is_array($update_dpa_request) && count($update_dpa_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $update_dpa_request when calling updateMerchant'
            );
        }



        $resourcePath = '/org/{organization_id}/dpas/{srci_dpa_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($correlation_id !== null) {
            $headerParams['correlation-id'] = ObjectSerializer::toHeaderValue($correlation_id);
        }

        // path params
        if ($organization_id !== null) {
            $resourcePath = str_replace(
                '{' . 'organization_id' . '}',
                ObjectSerializer::toPathValue($organization_id),
                $resourcePath
            );
        }
        // path params
        if ($srci_dpa_id !== null) {
            $resourcePath = str_replace(
                '{' . 'srci_dpa_id' . '}',
                ObjectSerializer::toPathValue($srci_dpa_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($update_dpa_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($update_dpa_request));
            } else {
                $httpBody = $update_dpa_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation uploadMerchants
     *
     * API to register a merchant and Store DPA (digital payment application) bulk load data
     *
     * @param  string $organization_id ID of the SRC system where a merchant is registered. (required)
     * @param  \MastercardApiClient\Model\DpaRequest $dpa_request dpa_request (required)
     * @param  string $correlation_id Unique Id to trace one end to end transaction, Client to ensure uniqueness for every transaction (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['uploadMerchants'] to see the possible values for this operation
     *
     * @throws \MastercardApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \MastercardApiClient\Model\DpaResponse|\MastercardApiClient\Model\Error|\MastercardApiClient\Model\Error|\MastercardApiClient\Model\Error|\MastercardApiClient\Model\Error
     */
    public function uploadMerchants($organization_id, $dpa_request, $correlation_id = null, string $contentType = self::contentTypes['uploadMerchants'][0])
    {
        list($response) = $this->uploadMerchantsWithHttpInfo($organization_id, $dpa_request, $correlation_id, $contentType);
        return $response;
    }

    /**
     * Operation uploadMerchantsWithHttpInfo
     *
     * API to register a merchant and Store DPA (digital payment application) bulk load data
     *
     * @param  string $organization_id ID of the SRC system where a merchant is registered. (required)
     * @param  \MastercardApiClient\Model\DpaRequest $dpa_request (required)
     * @param  string $correlation_id Unique Id to trace one end to end transaction, Client to ensure uniqueness for every transaction (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['uploadMerchants'] to see the possible values for this operation
     *
     * @throws \MastercardApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \MastercardApiClient\Model\DpaResponse|\MastercardApiClient\Model\Error|\MastercardApiClient\Model\Error|\MastercardApiClient\Model\Error|\MastercardApiClient\Model\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function uploadMerchantsWithHttpInfo($organization_id, $dpa_request, $correlation_id = null, string $contentType = self::contentTypes['uploadMerchants'][0])
    {
        $request = $this->uploadMerchantsRequest($organization_id, $dpa_request, $correlation_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\MastercardApiClient\Model\DpaResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\MastercardApiClient\Model\DpaResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\MastercardApiClient\Model\DpaResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\MastercardApiClient\Model\Error' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\MastercardApiClient\Model\Error' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\MastercardApiClient\Model\Error', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\MastercardApiClient\Model\Error' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\MastercardApiClient\Model\Error' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\MastercardApiClient\Model\Error', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 403:
                    if ('\MastercardApiClient\Model\Error' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\MastercardApiClient\Model\Error' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\MastercardApiClient\Model\Error', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\MastercardApiClient\Model\Error' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\MastercardApiClient\Model\Error' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\MastercardApiClient\Model\Error', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\MastercardApiClient\Model\DpaResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MastercardApiClient\Model\DpaResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MastercardApiClient\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MastercardApiClient\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MastercardApiClient\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MastercardApiClient\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation uploadMerchantsAsync
     *
     * API to register a merchant and Store DPA (digital payment application) bulk load data
     *
     * @param  string $organization_id ID of the SRC system where a merchant is registered. (required)
     * @param  \MastercardApiClient\Model\DpaRequest $dpa_request (required)
     * @param  string $correlation_id Unique Id to trace one end to end transaction, Client to ensure uniqueness for every transaction (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['uploadMerchants'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function uploadMerchantsAsync($organization_id, $dpa_request, $correlation_id = null, string $contentType = self::contentTypes['uploadMerchants'][0])
    {
        return $this->uploadMerchantsAsyncWithHttpInfo($organization_id, $dpa_request, $correlation_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation uploadMerchantsAsyncWithHttpInfo
     *
     * API to register a merchant and Store DPA (digital payment application) bulk load data
     *
     * @param  string $organization_id ID of the SRC system where a merchant is registered. (required)
     * @param  \MastercardApiClient\Model\DpaRequest $dpa_request (required)
     * @param  string $correlation_id Unique Id to trace one end to end transaction, Client to ensure uniqueness for every transaction (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['uploadMerchants'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function uploadMerchantsAsyncWithHttpInfo($organization_id, $dpa_request, $correlation_id = null, string $contentType = self::contentTypes['uploadMerchants'][0])
    {
        $returnType = '\MastercardApiClient\Model\DpaResponse';
        $request = $this->uploadMerchantsRequest($organization_id, $dpa_request, $correlation_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'uploadMerchants'
     *
     * @param  string $organization_id ID of the SRC system where a merchant is registered. (required)
     * @param  \MastercardApiClient\Model\DpaRequest $dpa_request (required)
     * @param  string $correlation_id Unique Id to trace one end to end transaction, Client to ensure uniqueness for every transaction (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['uploadMerchants'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function uploadMerchantsRequest($organization_id, $dpa_request, $correlation_id = null, string $contentType = self::contentTypes['uploadMerchants'][0])
    {

        // verify the required parameter 'organization_id' is set
        if ($organization_id === null || (is_array($organization_id) && count($organization_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $organization_id when calling uploadMerchants'
            );
        }

        // verify the required parameter 'dpa_request' is set
        if ($dpa_request === null || (is_array($dpa_request) && count($dpa_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $dpa_request when calling uploadMerchants'
            );
        }



        $resourcePath = '/org/{organization_id}/dpas/batch';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($correlation_id !== null) {
            $headerParams['correlation-id'] = ObjectSerializer::toHeaderValue($correlation_id);
        }

        // path params
        if ($organization_id !== null) {
            $resourcePath = str_replace(
                '{' . 'organization_id' . '}',
                ObjectSerializer::toPathValue($organization_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($dpa_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($dpa_request));
            } else {
                $httpBody = $dpa_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
