<?php
/**
 * CheckoutToken
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  MastercardApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Checkout, Save Card On File, Delete Saved Card On File And Confirmations API
 *
 * Click to Pay checkout used by Merchants to receive payload data from the Click to Pay System and send the results of transaction authorisation back to the Click to Pay System. Endpoints are available to retrieve payload data and send the outcome of a payment or checkout.  The signing of the request is as per the process documented at [https://developer.mastercard.com/support-article/what-authentication-requirements-are-there-to-use-the-raw-rest-protocol](https://developer.mastercard.com/support-article/what-authentication-requirements-are-there-to-use-the-raw-rest-protocol)  The signing process and calcualtion of body hash follows draft given by Google and documented at [https://tools.ietf.org/id/draft-eaton-oauth-bodyhash-00.html](https://tools.ietf.org/id/draft-eaton-oauth-bodyhash-00.html)
 *
 * The version of the OpenAPI document: 1.3.2
 * Contact: apisupport@mastercard.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace MastercardApiClient\Model;

use \ArrayAccess;
use \MastercardApiClient\ObjectSerializer;

/**
 * CheckoutToken Class Doc Comment
 *
 * @category Class
 * @package  MastercardApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CheckoutToken implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CheckoutToken';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'payment_token' => 'string',
        'token_expiration_month' => 'string',
        'token_expiration_year' => 'string',
        'payment_account_reference' => 'string',
        'cardholder_full_name' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'payment_token' => null,
        'token_expiration_month' => null,
        'token_expiration_year' => null,
        'payment_account_reference' => null,
        'cardholder_full_name' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'payment_token' => false,
		'token_expiration_month' => false,
		'token_expiration_year' => false,
		'payment_account_reference' => false,
		'cardholder_full_name' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'payment_token' => 'paymentToken',
        'token_expiration_month' => 'tokenExpirationMonth',
        'token_expiration_year' => 'tokenExpirationYear',
        'payment_account_reference' => 'paymentAccountReference',
        'cardholder_full_name' => 'cardholderFullName'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'payment_token' => 'setPaymentToken',
        'token_expiration_month' => 'setTokenExpirationMonth',
        'token_expiration_year' => 'setTokenExpirationYear',
        'payment_account_reference' => 'setPaymentAccountReference',
        'cardholder_full_name' => 'setCardholderFullName'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'payment_token' => 'getPaymentToken',
        'token_expiration_month' => 'getTokenExpirationMonth',
        'token_expiration_year' => 'getTokenExpirationYear',
        'payment_account_reference' => 'getPaymentAccountReference',
        'cardholder_full_name' => 'getCardholderFullName'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('payment_token', $data ?? [], null);
        $this->setIfExists('token_expiration_month', $data ?? [], null);
        $this->setIfExists('token_expiration_year', $data ?? [], null);
        $this->setIfExists('payment_account_reference', $data ?? [], null);
        $this->setIfExists('cardholder_full_name', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['payment_token'] === null) {
            $invalidProperties[] = "'payment_token' can't be null";
        }
        if (!is_null($this->container['token_expiration_month']) && (mb_strlen($this->container['token_expiration_month']) > 2)) {
            $invalidProperties[] = "invalid value for 'token_expiration_month', the character length must be smaller than or equal to 2.";
        }

        if (!is_null($this->container['token_expiration_year']) && (mb_strlen($this->container['token_expiration_year']) > 4)) {
            $invalidProperties[] = "invalid value for 'token_expiration_year', the character length must be smaller than or equal to 4.";
        }

        if (!is_null($this->container['payment_account_reference']) && (mb_strlen($this->container['payment_account_reference']) > 29)) {
            $invalidProperties[] = "invalid value for 'payment_account_reference', the character length must be smaller than or equal to 29.";
        }

        if (!is_null($this->container['cardholder_full_name']) && (mb_strlen($this->container['cardholder_full_name']) > 100)) {
            $invalidProperties[] = "invalid value for 'cardholder_full_name', the character length must be smaller than or equal to 100.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets payment_token
     *
     * @return string
     */
    public function getPaymentToken()
    {
        return $this->container['payment_token'];
    }

    /**
     * Sets payment_token
     *
     * @param string $payment_token < Payment Token. ISO/IEC 7812 format
     *
     * @return self
     */
    public function setPaymentToken($payment_token)
    {
        if (is_null($payment_token)) {
            throw new \InvalidArgumentException('non-nullable payment_token cannot be null');
        }
        $this->container['payment_token'] = $payment_token;

        return $this;
    }

    /**
     * Gets token_expiration_month
     *
     * @return string|null
     */
    public function getTokenExpirationMonth()
    {
        return $this->container['token_expiration_month'];
    }

    /**
     * Sets token_expiration_month
     *
     * @param string|null $token_expiration_month < Two-digit expiry month (MM) Conditionality- Supplied when specified for the Payment Token.
     *
     * @return self
     */
    public function setTokenExpirationMonth($token_expiration_month)
    {
        if (is_null($token_expiration_month)) {
            throw new \InvalidArgumentException('non-nullable token_expiration_month cannot be null');
        }
        if ((mb_strlen($token_expiration_month) > 2)) {
            throw new \InvalidArgumentException('invalid length for $token_expiration_month when calling CheckoutToken., must be smaller than or equal to 2.');
        }

        $this->container['token_expiration_month'] = $token_expiration_month;

        return $this;
    }

    /**
     * Gets token_expiration_year
     *
     * @return string|null
     */
    public function getTokenExpirationYear()
    {
        return $this->container['token_expiration_year'];
    }

    /**
     * Sets token_expiration_year
     *
     * @param string|null $token_expiration_year < Four-digit expiry year (YYYY) Conditionality- Supplied when specified for the Payment Token
     *
     * @return self
     */
    public function setTokenExpirationYear($token_expiration_year)
    {
        if (is_null($token_expiration_year)) {
            throw new \InvalidArgumentException('non-nullable token_expiration_year cannot be null');
        }
        if ((mb_strlen($token_expiration_year) > 4)) {
            throw new \InvalidArgumentException('invalid length for $token_expiration_year when calling CheckoutToken., must be smaller than or equal to 4.');
        }

        $this->container['token_expiration_year'] = $token_expiration_year;

        return $this;
    }

    /**
     * Gets payment_account_reference
     *
     * @return string|null
     */
    public function getPaymentAccountReference()
    {
        return $this->container['payment_account_reference'];
    }

    /**
     * Sets payment_account_reference
     *
     * @param string|null $payment_account_reference < Payment Account Reference. A non-financial reference assigned to each unique PAN and used to link a Payment Account represented by that PAN to affiliated Payment Tokens.
     *
     * @return self
     */
    public function setPaymentAccountReference($payment_account_reference)
    {
        if (is_null($payment_account_reference)) {
            throw new \InvalidArgumentException('non-nullable payment_account_reference cannot be null');
        }
        if ((mb_strlen($payment_account_reference) > 29)) {
            throw new \InvalidArgumentException('invalid length for $payment_account_reference when calling CheckoutToken., must be smaller than or equal to 29.');
        }

        $this->container['payment_account_reference'] = $payment_account_reference;

        return $this;
    }

    /**
     * Gets cardholder_full_name
     *
     * @return string|null
     */
    public function getCardholderFullName()
    {
        return $this->container['cardholder_full_name'];
    }

    /**
     * Sets cardholder_full_name
     *
     * @param string|null $cardholder_full_name Cardholder Name.
     *
     * @return self
     */
    public function setCardholderFullName($cardholder_full_name)
    {
        if (is_null($cardholder_full_name)) {
            throw new \InvalidArgumentException('non-nullable cardholder_full_name cannot be null');
        }
        if ((mb_strlen($cardholder_full_name) > 100)) {
            throw new \InvalidArgumentException('invalid length for $cardholder_full_name when calling CheckoutToken., must be smaller than or equal to 100.');
        }

        $this->container['cardholder_full_name'] = $cardholder_full_name;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


