<?php
/**
 * CheckoutType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  MastercardApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Checkout, Save Card On File, Delete Saved Card On File And Confirmations API
 *
 * Click to Pay checkout used by Merchants to receive payload data from the Click to Pay System and send the results of transaction authorisation back to the Click to Pay System. Endpoints are available to retrieve payload data and send the outcome of a payment or checkout.  The signing of the request is as per the process documented at [https://developer.mastercard.com/support-article/what-authentication-requirements-are-there-to-use-the-raw-rest-protocol](https://developer.mastercard.com/support-article/what-authentication-requirements-are-there-to-use-the-raw-rest-protocol)  The signing process and calcualtion of body hash follows draft given by Google and documented at [https://tools.ietf.org/id/draft-eaton-oauth-bodyhash-00.html](https://tools.ietf.org/id/draft-eaton-oauth-bodyhash-00.html)
 *
 * The version of the OpenAPI document: 1.3.2
 * Contact: apisupport@mastercard.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace MastercardApiClient\Model;
use \MastercardApiClient\ObjectSerializer;

/**
 * CheckoutType Class Doc Comment
 *
 * @category Class
 * @description Checkout Type, Request will only be processed when appropriate &#39;checkoutType&#39; is associated with DPA. If it is not passed, it will default to CLICK_TO_PAY.
 * @package  MastercardApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CheckoutType
{
    /**
     * Possible values of this enum
     */
    public const CLICK_TO_PAY = 'CLICK_TO_PAY';

    public const CARD_ON_FILE_TOKENIZATION = 'CARD_ON_FILE_TOKENIZATION';

    public const GUEST_CHECKOUT_TOKENIZATION = 'GUEST_CHECKOUT_TOKENIZATION';

    public const INSTALLMENTS = 'INSTALLMENTS';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::CLICK_TO_PAY,
            self::CARD_ON_FILE_TOKENIZATION,
            self::GUEST_CHECKOUT_TOKENIZATION,
            self::INSTALLMENTS
        ];
    }
}


