<?php
/**
 * ThreeDSDefaultData
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  MastercardApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Srci Client Onboarding Orch Service API
 *
 * Mastercard Commerce System:  API definitions for Client Onboarding Orch Service.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@mastercard.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace MastercardApiClient\Model;

use \ArrayAccess;
use \MastercardApiClient\ObjectSerializer;

/**
 * ThreeDSDefaultData Class Doc Comment
 *
 * @category Class
 * @description This data set will allow merchant to onboard themselves with 3DS default configuration and they will be able to pass 3DS configuration run time as well.
 * @package  MastercardApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ThreeDSDefaultData implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ThreeDSDefaultData';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'default_acquirer_bin' => 'string',
        'default_acquirer_merchant_id' => 'string',
        'default_merchant_category_code' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'default_acquirer_bin' => null,
        'default_acquirer_merchant_id' => null,
        'default_merchant_category_code' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'default_acquirer_bin' => false,
		'default_acquirer_merchant_id' => false,
		'default_merchant_category_code' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'default_acquirer_bin' => 'defaultAcquirerBin',
        'default_acquirer_merchant_id' => 'defaultAcquirerMerchantId',
        'default_merchant_category_code' => 'defaultMerchantCategoryCode'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'default_acquirer_bin' => 'setDefaultAcquirerBin',
        'default_acquirer_merchant_id' => 'setDefaultAcquirerMerchantId',
        'default_merchant_category_code' => 'setDefaultMerchantCategoryCode'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'default_acquirer_bin' => 'getDefaultAcquirerBin',
        'default_acquirer_merchant_id' => 'getDefaultAcquirerMerchantId',
        'default_merchant_category_code' => 'getDefaultMerchantCategoryCode'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('default_acquirer_bin', $data ?? [], null);
        $this->setIfExists('default_acquirer_merchant_id', $data ?? [], null);
        $this->setIfExists('default_merchant_category_code', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets default_acquirer_bin
     *
     * @return string|null
     */
    public function getDefaultAcquirerBin()
    {
        return $this->container['default_acquirer_bin'];
    }

    /**
     * Sets default_acquirer_bin
     *
     * @param string|null $default_acquirer_bin The bank identification number assigned by Mastercard to the respective acquirer to identify the acquirer. If this is not populated & acquirerData has only one entry, this field will be populated with 'acquirerData.acquirerBin'.
     *
     * @return self
     */
    public function setDefaultAcquirerBin($default_acquirer_bin)
    {
        if (is_null($default_acquirer_bin)) {
            throw new \InvalidArgumentException('non-nullable default_acquirer_bin cannot be null');
        }
        $this->container['default_acquirer_bin'] = $default_acquirer_bin;

        return $this;
    }

    /**
     * Gets default_acquirer_merchant_id
     *
     * @return string|null
     */
    public function getDefaultAcquirerMerchantId()
    {
        return $this->container['default_acquirer_merchant_id'];
    }

    /**
     * Sets default_acquirer_merchant_id
     *
     * @param string|null $default_acquirer_merchant_id The default ID that acquirer assigns to merchants. If this field is not populated & acquirerData has only one entry, this field will be populated with 'acquirerData.acquirerMerchantId'.
     *
     * @return self
     */
    public function setDefaultAcquirerMerchantId($default_acquirer_merchant_id)
    {
        if (is_null($default_acquirer_merchant_id)) {
            throw new \InvalidArgumentException('non-nullable default_acquirer_merchant_id cannot be null');
        }
        $this->container['default_acquirer_merchant_id'] = $default_acquirer_merchant_id;

        return $this;
    }

    /**
     * Gets default_merchant_category_code
     *
     * @return string|null
     */
    public function getDefaultMerchantCategoryCode()
    {
        return $this->container['default_merchant_category_code'];
    }

    /**
     * Sets default_merchant_category_code
     *
     * @param string|null $default_merchant_category_code The category code captured at DPA level. If this is not populated & merchantCategoryCode has only one entry, this field will be populated with merchantCategoryCode[0].
     *
     * @return self
     */
    public function setDefaultMerchantCategoryCode($default_merchant_category_code)
    {
        if (is_null($default_merchant_category_code)) {
            throw new \InvalidArgumentException('non-nullable default_merchant_category_code cannot be null');
        }
        $this->container['default_merchant_category_code'] = $default_merchant_category_code;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


