<?php
/**
 * MerchantRegistrationApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  MastercardApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Srci Client Onboarding Orch Service API
 *
 * Mastercard Commerce System:  API definitions for Client Onboarding Orch Service.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@mastercard.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace MastercardApiClient\Test\Api;

use \MastercardApiClient\Configuration;
use \MastercardApiClient\ApiException;
use \MastercardApiClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * MerchantRegistrationApiTest Class Doc Comment
 *
 * @category Class
 * @package  MastercardApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MerchantRegistrationApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for deleteMerchant
     *
     * Delete merchant from Unified Checkout Solutions.
     *
     */
    public function testDeleteMerchant()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateMerchant
     *
     * Update DPA data.
     *
     */
    public function testUpdateMerchant()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for uploadMerchants
     *
     * API to register a merchant and Store DPA (digital payment application) bulk load data.
     *
     */
    public function testUploadMerchants()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
